---
engines:
  duplication:
    enabled: true
    config:
      languages:
      - ruby
  brakeman:
    enabled: true
  bundler-audit:
    enabled: true
  fixme:
    enabled: true
  rubocop:
    enabled: true
  markdownlint:
    enabled: true
ratings:
  paths:
  - "**.rb"
  - "**.md"
exclude_paths: []
